import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import SyncUserConvex from "@/components/sync-user";
import { Toaster } from "sonner";
import { EdgeStoreProvider } from "@/components/edgestore/edgestore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SnapNotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ConvexClientProvider>
        <SyncUserConvex />
        <EdgeStoreProvider>
        <Toaster position="top-center" />
        {children}
        </EdgeStoreProvider>
       </ConvexClientProvider>
      </body>
    </html>
  );
}
